repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.2
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      - id: ruff
        args: [--fix,  --unsafe-fixes]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.7
    hooks:
      - id: clang-format
        types_or: [c, c++]
        exclude: ^\.venv/

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17  # Use latest version
    hooks:
    - id: mdformat
      exclude: ^(examples/|src/just_makeit/examples/)
      # Add optional plugins (e.g., for GFM or code block formatting)
      additional_dependencies:
      - mdformat-gfm
