#include "/*<<component>>*///*<<component>>*/_core.h"
#include <complex.h>
#include <math.h>
#include <stdio.h>

/* gh-806: how many assertions just-makeit generated into this file.  Stamped
 * at scaffold time and compared against the runtime count below, so the
 * "scaffold coverage only" banner clears itself the moment an author adds a
 * check of their own -- a hard-coded marker would still be claiming to be a
 * placeholder long after the real suite was written. */
#define JM_SCAFFOLD_CHECKS /*<<scaffold_checks>>*/

static int _checks = 0;

#define CHECK(cond) \
    do { _checks++; if (!(cond)) { \
        fprintf(stderr, "FAIL %s:%d  %s\n", __FILE__, __LINE__, #cond); \
        _fails++; \
    } } while (0)

/* Floating-point helpers — use inline functions, not macros, so arguments
 * are evaluated exactly once.  Safe to call with stateful step() results. */
static inline int _almost_eq(float a, float b, float tol)
    { return fabsf(a - b) <= tol; }
static inline int _almost_eq_c(float complex a, float complex b, float tol)
    { return _almost_eq(crealf(a), crealf(b), tol)
          && _almost_eq(cimagf(a), cimagf(b), tol); }
#define ALMOST_EQ(a, b, tol)   _almost_eq((float)(a),         (float)(b),         tol)
#define ALMOST_EQ_C(a, b, tol) _almost_eq_c((float complex)(a), (float complex)(b), tol)

int main(void)
{
    int _fails = 0;
    /*<<component>>*/_state_t *obj = /*<<component>>*/_create(/*<<c_create_args>>*/);
/*<<obj_null_check>>*/

/*<<getter_setter_test_c>>*/

/*<<step_c_smoke_test>>*/

/*<<reset_test_c>>*/

    /*<<component>>*/_destroy(obj);
    if (_fails) {
        fprintf(stderr, "test_/*<<component>>*/_core FAILED (%d of %d)\n",
                _fails, _checks);
        return 1;
    }
    /* gh-806: the count is the point.  A renamed component orphans its real
     * suite and a fresh scaffold takes over the CTest target -- and because
     * the scaffold passes, "100% tests passed" is still what CI prints.  The
     * one thing that distinguishes the two in a log is how much was actually
     * asserted, so say it. */
    printf("test_/*<<component>>*/_core PASSED (%d checks)\n", _checks);
    /* Deliberately does not enumerate what the scaffold covers: that varies
     * with the component's shape, and naming the parts would put words like
     * the lifecycle hooks into a file generated for components that were
     * asked not to have them (gh-542). */
    if (_checks <= JM_SCAFFOLD_CHECKS)
        printf("  NOTE: scaffold coverage only -- every check above was"
               " generated by\n        just-makeit; no test suite has been"
               " added to this file yet.\n");
    return 0;
}
