/**
 * /*<<package>>*/.h — umbrella header for the /*<<package>>*/ C library.
 *
 * Include this header to access all component APIs, or include
 * individual component headers directly.
 *
 * Generated by just-makeit; updated on each `just-makeit init`.
 *
 * gh-1148: the component includes below are deliberately NOT wrapped in an
 * `extern "C"` block. They used to be, and it made this the one generated
 * header a C++ translation unit could not include.
 *
 * Every component header opens its own `extern "C"` guard, so the wrapper
 * here added nothing -- this file declares no function of its own. What it
 * did add was harm: each component header includes `clib_common.h`, so
 * `<complex.h>`, `<stdlib.h>` and `<string.h>` all landed INSIDE `extern
 * "C"`. Including a C++ standard header there is ill-formed. libstdc++
 * tolerates it and libc++ does not, so this compiled on Linux and failed on
 * macOS -- for a header that had been that way since the umbrella was
 * written.
 */
#ifndef /*<<PACKAGE>>*/_H
#define /*<<PACKAGE>>*/_H

/* ── Components ─────────────────────────────────────────────────────────── */

#endif /* /*<<PACKAGE>>*/_H */
