/**
 * /*<<package>>*/.h — umbrella header for the /*<<package>>*/ C library.
 *
 * Include this header to access all component APIs, or include
 * individual component headers directly.
 *
 * Generated by just-makeit; updated on each `just-makeit init`.
 */
#ifndef /*<<PACKAGE>>*/_H
#define /*<<PACKAGE>>*/_H

#ifdef __cplusplus
extern "C" {
#endif

/* ── Components ─────────────────────────────────────────────────────────── */

#ifdef __cplusplus
}
#endif

#endif /* /*<<PACKAGE>>*/_H */
