"""gh-1660: a refused `jm apply` -- or `jm upgrade` -- writes nothing.

`apply` stamped ``[project] jm_version`` (gh-183) before any of its
refusals were asked, so on a project an OLDER jm had generated, every
refusal still rewrote the manifest: measured on doppler (``0.75.5``), a
gh-1657 collision exited 1 and left ``jm_version = "0.91.0"`` behind --
a record that this jm had generated a project it had refused to touch. The
existing gh-1657 gate could not see it: its project was generated by the
running jm, so the stamp had nothing to change. Every fixture here is aged
first, which is the precondition the bug needs.

The stamp now follows the last refusal. Composing a fragment
(`jm apply <fragment.toml>`) is the other write that has to precede the
refusals -- they read the manifest WITH the fragment -- so what composing
wrote is undone when one follows. And
`upgrade` asked "was the prefix removed?" only after its migrations and
`_rename_superseded` had written; it is asked first now, with the gh-1657
collision.

GATE: on a project generated by an older jm, each refusal `apply` asks --
      a gh-1657 collision, a removed prefix, an unsupported type, an empty
      manifest, an unknown `--only`, an owned fragment that would lose code,
      and one after composing a fragment -- and `upgrade`'s removed-prefix
      refusal exit 1 and leave the WHOLE tree byte-identical; an apply that
      succeeds still stamps the running version.
"""

from __future__ import annotations

import re
import shutil
from pathlib import Path

import pytest

from _jmrun import run_cli
from just_makeit import _config as C
from just_makeit import _textio

#: Older than any jm that can run this test, so the stamp always has
#: something to change.
OLD = "0.1.0"

#: The author's wrapper under the name `c_prefix = "zz"` derives from
#: `lo`'s method `scale` -- the gh-1657 collision.
WRAP = (
    "native/src/lo/lo_wrap.c",
    '#include "q/lo/lo_core.h"\n'
    "\n"
    "float\n"
    "zz_lo_scale (lo_state_t *state, float x)\n"
    "{\n"
    "  return lo_scale (state, x);\n"
    "}\n",
)

#: The fragment module object `blk` lives in, and its binding fragment.
BLK_TOML = Path("objects") / "blk.toml"
BLK_FRAG = Path("native") / "src" / "m" / "m_ext_blk.c"


def _ok(*args: str, cwd: Path) -> None:
    r = run_cli(*args, cwd=cwd)
    assert r.returncode == 0, (args, r.stdout + r.stderr)


def _build(where: Path, *new_flags: str) -> Path:
    """A project built by running jm: standalone `lo` with a method
    `scale`, and module `m` holding `blk` with one method."""
    _ok("new", "q", *new_flags, cwd=where)
    root = where / "q"
    _ok("object", "lo", "--state", "gain:float:2.0", cwd=root)
    _ok(
        "method",
        "lo",
        "scale",
        "--arg-type",
        "float",
        "--return-type",
        "float",
        cwd=root,
    )
    _ok("module", "m", cwd=root)
    _ok("object", "blk", "--module", "m", "--no-state", "--no-step", cwd=root)
    _ok(
        "method",
        "blk",
        "execute",
        "--module",
        "m",
        "--arg-type",
        "float",
        "--return-type",
        "float",
        "--variable-output",
        cwd=root,
    )
    _ok("apply", cwd=root)
    return root


@pytest.fixture(scope="module")
def plain(tmp_path_factory) -> Path:
    return _build(tmp_path_factory.mktemp("g1660p"), "--no-c-prefix")


@pytest.fixture(scope="module")
def prefixed(tmp_path_factory) -> Path:
    return _build(tmp_path_factory.mktemp("g1660z"), "--c-prefix", "zz")


def _copy(src: Path, where: Path) -> Path:
    """*src*, aged: its manifest says an older jm generated it."""
    root = where / "q"
    shutil.copytree(src, root)
    _edit(
        root / C.FILENAME, r'(?m)^jm_version = ".*"$', f'jm_version = "{OLD}"'
    )
    return root


def _edit(path: Path, pattern: str, repl: str) -> None:
    """Exactly one match, replaced -- a fixture edit that lands nowhere
    would turn a refusal test into a no-op."""
    text = path.read_text(encoding="utf-8")
    new, n = re.subn(pattern, repl, text, count=1)
    assert n == 1, (path, pattern)
    _textio.write_text(path, new)


def _snapshot(root: Path) -> "dict[str, bytes]":
    """Every file under *root*, and every directory as an empty marker."""
    out = {}
    for p in sorted(root.rglob("*")):
        if "__pycache__" in p.parts:
            continue
        rel = p.relative_to(root).as_posix()
        out[rel] = p.read_bytes() if p.is_file() else b"<dir>"
    return out


def _refused_and_untouched(root: Path, *args: str, says: str) -> None:
    before = _snapshot(root)
    r = run_cli(*args, cwd=root)
    out = r.stdout + r.stderr
    assert r.returncode == 1, out
    # The refusal the case is named for, not some other one.
    assert says in out, out
    after = _snapshot(root)
    changed = sorted(
        k
        for k in before.keys() | after.keys()
        if before.get(k) != after.get(k)
    )
    assert changed == [], changed


# -- the refusals, one per kind ---------------------------------------------


def _collision(root: Path) -> str:
    _textio.write_text(root / WRAP[0], WRAP[1])
    _edit(
        root / C.FILENAME,
        r"(?m)^\[project\]\n",
        '[project]\nc_prefix = "zz"\n',
    )
    return "already declares `zz_lo_scale`"


def _removed_prefix(root: Path) -> str:
    _edit(root / C.FILENAME, r'(?m)^c_prefix = "zz"\n', "")
    return "c_prefix is no longer set"


def _bad_type(root: Path) -> str:
    _edit(
        root / "objects" / "lo.toml",
        r'(?m)^return_type = "float"$',
        'return_type = "notatype"',
    )
    return "unsupported type"


def _owned_would_lose(root: Path) -> str:
    frag = root / BLK_FRAG
    _textio.write_text(
        frag,
        frag.read_text(encoding="utf-8")
        + "\nstatic PyObject *\nBlkObj_mine(PyObject *s)\n"
        "{\n    return NULL;\n}\n",
    )
    _edit(root / BLK_TOML, r"(?m)^\[blk\]$", '[blk]\nfragment = "generated"')
    return "never rendered whole"


REFUSALS = {
    "collision": ("plain", _collision),
    "removed_prefix": ("prefixed", _removed_prefix),
    "bad_type": ("plain", _bad_type),
    "owned_would_lose": ("plain", _owned_would_lose),
}


@pytest.mark.parametrize("kind", sorted(REFUSALS))
def test_a_refused_apply_writes_nothing(kind, plain, prefixed, tmp_path):
    which, cause = REFUSALS[kind]
    root = _copy({"plain": plain, "prefixed": prefixed}[which], tmp_path)
    says = cause(root)
    _refused_and_untouched(root, "apply", says=says)


def test_an_unknown_only_writes_nothing(plain, tmp_path):
    root = _copy(plain, tmp_path)
    _refused_and_untouched(
        root, "apply", "--only=nosuch", says="is not a known module"
    )


def test_an_empty_manifest_writes_nothing(tmp_path):
    _ok("new", "q", cwd=tmp_path)
    root = tmp_path / "q"
    _edit(
        root / C.FILENAME, r'(?m)^jm_version = ".*"$', f'jm_version = "{OLD}"'
    )
    _refused_and_untouched(root, "apply", says="declares no objects")


def test_a_refusal_after_composing_a_fragment_undoes_it(tmp_path):
    """Composing writes before the refusals are asked. On a single-manifest
    project it writes all three things it can: the `objects/` directory,
    the copy in it, and the manifest's `include` line."""
    _ok("new", "q", "--no-fragments", cwd=tmp_path)
    root = tmp_path / "q"
    _ok("object", "lo", "--state", "gain:float:2.0", cwd=root)
    _ok("apply", cwd=root)
    assert not (root / "objects").exists()
    _edit(
        root / C.FILENAME, r'(?m)^jm_version = ".*"$', f'jm_version = "{OLD}"'
    )
    incoming = tmp_path / "extra.toml"
    _textio.write_text(
        incoming,
        '[extra]\narg_type = "float"\nreturn_type = "float"\n\n'
        '[[extra.methods]]\nname = "go"\narg_type = "float"\n'
        'return_type = "notatype"\n',
    )
    _refused_and_untouched(
        root, "apply", str(incoming), says="unsupported type"
    )


def test_a_refused_upgrade_writes_nothing(prefixed, tmp_path):
    """A removed prefix was asked only in the c_prefix repair, after
    `_rename_superseded` had moved `jb.toml` (gh-1472)."""
    root = _copy(prefixed, tmp_path)
    _removed_prefix(root)
    (root / "bootstrap.toml").rename(root / "jb.toml")
    _refused_and_untouched(root, "upgrade", says="c_prefix is no longer set")


# -- the other direction ----------------------------------------------------


def test_an_apply_that_succeeds_still_stamps(plain, tmp_path):
    root = _copy(plain, tmp_path)
    _ok("apply", cwd=root)
    assert C.jm_version(C.load(root)) == C.jm_cli_version()


def test_a_fragment_stays_once_the_reconcile_has_written(
    plain, tmp_path, monkeypatch
):
    """A refusal AFTER the reconcile's first write does not undo the
    fragment: the tree is no longer the one it was composed into, and a
    manifest without it would describe files it did not generate."""
    from just_makeit import _apply

    def _refuse(*a, **k):
        raise ValueError("forced reconcile refusal")

    root = _copy(plain, tmp_path)
    incoming = tmp_path / "extra.toml"
    _textio.write_text(
        incoming, '[extra]\narg_type = "float"\nreturn_type = "float"\n'
    )
    monkeypatch.setattr(_apply, "_sync_aggregates", _refuse)
    r = run_cli("apply", str(incoming), cwd=root)
    assert r.returncode == 1, r.stdout + r.stderr
    assert "forced reconcile refusal" in r.stderr, r.stderr
    assert (root / "objects" / "extra.toml").is_file()
    assert "extra" in C.components(C.load(root))
