[build-system]
requires = ["just-buildit", "numpy"]
build-backend = "just_buildit"

[project]
name = "my-project"
version = "0.1.0"
description = "TODO: describe your project."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "pytest-benchmark",
]

[tool.just-buildit]
command = "make just-build"

[tool.pytest.ini_options]
testpaths = ["src"]
markers = [
    "benchmark: mark test as a benchmark (requires pytest-benchmark)",
]
