/**
 * stale.h — umbrella header for the stale C library.
 *
 * Include this header to access all component APIs, or include
 * individual component headers directly.
 *
 * Generated by just-makeit; updated on each `just-makeit init`.
 */
#ifndef STALE_H
#define STALE_H

#ifdef __cplusplus
extern "C" {
#endif

/* ── Components ─────────────────────────────────────────────────────────── */

#include "gain/gain_core.h"

#include "fir/fir_core.h"

#ifdef __cplusplus
}
#endif

#endif /* STALE_H */
