/**
 * my_project.h — umbrella header for the my_project C library.
 *
 * Include this header to access all component APIs, or include
 * individual component headers directly.
 *
 * Generated by just-makeit; updated on each `just-makeit init`.
 */
#ifndef MY_PROJECT_H
#define MY_PROJECT_H

#ifdef __cplusplus
extern "C" {
#endif

/* ── Components ─────────────────────────────────────────────────────────── */

#include "engine/engine_core.h"

#ifdef __cplusplus
}
#endif

#endif /* MY_PROJECT_H */
