#!/usr/bin/env python3
"""The CI toolchain image's pin: what it is built from, and whether it is owed.

An adopter with ``HAS_CI_IMAGE = 1`` runs its Linux CI jobs inside one image
per base (``CI_IMAGE_BASES``), built from the vendored ``docker/ci.Dockerfile``
and pinned by digest in ``.github/ci-images.env``. Every input to that image
is pinned in the same file, so a rebuild reproduces it and the toolchain a PR
is tested with changes only when a commit says so:

``CI_APT_SNAPSHOT``
    a snapshot.ubuntu.com timestamp; every apt source is rewritten to it.
``CI_BASE_<key>``
    each base image, by digest (``<key>`` is the version's digits:
    ``ubuntu:24.04`` -> ``2404``).
``CI_JB_VERSION`` / ``CI_JB_SHA256``
    the just-bashit release whose ``install-deps.sh`` installs the
    ``bootstrap.toml`` groups. Pinning ``jbx`` would pin nothing: it resolves
    install-deps through ``aliases.toml`` at run time.

and what was built from them:

``CI_IMAGE_<key>``
    the multi-arch index, by digest.
``CI_IMAGE_FINGERPRINT_<key>``
    a hash of every package and version in the image, over BOTH arches. A
    digest moves on every rebuild (timestamps, layer ids); this moves only
    when the content does, so it -- not the digest -- decides whether a
    rebuild owes a repin.
``CI_IMAGE_SOURCE_HASH``
    a hash of the files the image is built from (the Dockerfile, the
    optional ``docker/ci-extra.sh``, ``bootstrap.toml``). ``check`` refuses a
    tree whose sources moved without a repin. ``bootstrap.toml``'s
    ``[project]`` table is left out: no layer reads it, and it holds the
    release version, so hashing it made every version bump owe a full
    rebuild of every base on both arches (doppler-dsp/doppler#1765).

Only a refresh (the weekly run, or a dispatch asking for one) picks new
inputs; every other build reads the pinned ones.

Subcommands
-----------
``source-hash``
    Print this tree's ``CI_IMAGE_SOURCE_HASH``.
``inputs [--refresh]``
    Print the build inputs as ``KEY=VALUE`` lines: the pinned ones, or with
    ``--refresh`` today's (a new snapshot, each base's current digest, the
    latest just-bashit release and its asset's sha256).
``key BASE``
    Print a base's pin key (``ubuntu:24.04`` -> ``2404``).
``join-fingerprint FP...``
    Hash per-arch fingerprints, as ``arch=fp`` words, into one.
``write-pin --out FILE``
    Read ``KEY=VALUE`` lines on stdin and write a complete, ordered pin file.
``changed --new FILE``
    Exit 0 and print ``changed=1`` when FILE's fingerprints or source hash
    differ from the pin's, else ``changed=0``. The weekly run repins only on
    ``changed=1``: a new snapshot date alone is not a change.
``check``
    Fail unless the pin is complete and well formed and its source hash is
    this tree's.

Stdlib only, like every vendored script, so it runs before anything is
installed.

Examples
--------
>>> key("ubuntu:24.04")
'2404'
>>> join_fingerprint(["arm64=b", "amd64=a"]) == join_fingerprint(
...     ["amd64=a", "arm64=b"])
True
"""

from __future__ import annotations

import argparse
import datetime as _dt
import hashlib
import json
import os
import re
import subprocess
import sys
import urllib.request
from pathlib import Path

PIN = Path(".github/ci-images.env")
DOCKERFILE = Path("docker/ci.Dockerfile")
EXTRA = Path("docker/ci-extra.sh")
BOOTSTRAP = Path("bootstrap.toml")
JB_REPO = "just-buildit/just-bashit"
JB_ASSET = "just-bashit.tar.gz"

_DIGEST = r"sha256:[0-9a-f]{64}"
_SNAPSHOT = r"\d{8}T\d{6}Z"
_HEX64 = r"[0-9a-f]{64}"

HEADER = """\
# GENERATED by .github/workflows/ci-image.yml (scripts/ci-image.py) -- do
# not hand-edit. The CI toolchain image every Linux job runs in, pinned by
# digest, and every input it was built from, pinned beside it, so a rebuild
# reproduces it. `make ci-image-check` refuses a tree whose image sources
# moved without a repin.
"""


def bases() -> "list[str]":
    """``CI_IMAGE_BASES`` as make passes it, in order."""
    found = os.environ.get("CI_IMAGE_BASES", "").split()
    if not found:
        sys.exit("ci-image: CI_IMAGE_BASES is empty (set it in the Makefile)")
    return found


def key(base: str) -> str:
    """A base's pin key: the digits of its tag."""
    digits = re.sub(r"\D", "", base.split(":", 1)[-1].split("@", 1)[0])
    if not digits:
        sys.exit(f"ci-image: cannot derive a pin key from {base!r}")
    return digits


def read_pin(path: Path = PIN) -> "dict[str, str]":
    """The pin's ``KEY=VALUE`` lines; comments and blanks ignored."""
    if not path.exists():
        return {}
    out = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.strip() and not line.lstrip().startswith("#"):
            k, _, v = line.partition("=")
            out[k.strip()] = v.strip()
    return out


# A TOML table header on a line of its own: ``[a.b]`` or ``[[a.b]]``, keys
# bare or quoted, an optional trailing comment. Only read outside an array
# value: inside one, ``['project']`` alone on a line is an element, and
# reading it as a header would drop the lines after it unhashed.
_TABLE = re.compile(r"""^\s*\[\[?\s*([\w.\-"' ]+?)\s*\]\]?\s*(#.*)?$""")
# What brackets a line opens or closes cannot see inside: its strings, then
# its comment.
_NOT_BRACKETS = re.compile(r"""("(?:\\.|[^"\\])*"|'[^']*')|#.*""")


def _unread_by_the_image(name: str) -> bool:
    """Whether a table is one no image layer reads: ``[project]``, nested too.

    Excluding the one table nothing reads, rather than listing the ones the
    image does, is deliberate: an include-list silently misses a group a
    later ``bootstrap.toml`` adds. ``docker/ci-extra.sh`` is the adopter's
    and could read anything; one that reads ``[project]`` must say so in a
    table of its own.
    """
    first = name.split(".", 1)[0].strip().strip("\"'")
    return first == "project"


def _image_bytes(path: Path) -> bytes:
    """A source file's bytes as the image sees them.

    ``bootstrap.toml`` without its ``[project]`` table(s), every other byte
    kept: a comment or whitespace edit still owes a repin, which only ever
    errs toward rebuilding. A line filter rather than ``tomllib``, which
    needs Python 3.11 where this runs on the floor Python; one reading, not
    a parser with a fallback that could disagree with it.
    """
    if not path.exists():
        return b"<absent>"
    if path != BOOTSTRAP:
        return path.read_bytes()
    keep, depth, out = True, 0, []
    for line in path.read_bytes().decode("utf-8").splitlines(keepends=True):
        m = _TABLE.match(line) if depth == 0 else None
        if m:
            keep = not _unread_by_the_image(m.group(1))
        else:
            bare = _NOT_BRACKETS.sub("", line)
            depth = max(0, depth + bare.count("[") - bare.count("]"))
        if keep:
            out.append(line)
    return "".join(out).encode("utf-8")


def source_hash() -> str:
    """Hash every file the image is built from, by name and content."""
    h = hashlib.sha256()
    for path in (DOCKERFILE, EXTRA, BOOTSTRAP):
        h.update(str(path).encode() + b"\0")
        h.update(_image_bytes(path))
        h.update(b"\0")
    return h.hexdigest()


def join_fingerprint(words: "list[str]") -> str:
    """One fingerprint over every arch's, independent of their order."""
    return hashlib.sha256(
        "\n".join(sorted(words)).encode()
    ).hexdigest()


def _digest(ref: str) -> str:
    out = subprocess.run(
        ["docker", "buildx", "imagetools", "inspect", ref,
         "--format", "{{json .Manifest}}"],
        check=True, capture_output=True, text=True,
    ).stdout
    return json.loads(out)["digest"]


def _latest_jb() -> "tuple[str, str]":
    """The latest just-bashit release tag, and its asset's sha256."""
    req = urllib.request.Request(
        f"https://api.github.com/repos/{JB_REPO}/releases/latest",
        headers={"Accept": "application/vnd.github+json"},
    )
    token = os.environ.get("GH_TOKEN") or os.environ.get("GITHUB_TOKEN")
    if token:
        req.add_header("Authorization", f"Bearer {token}")
    with urllib.request.urlopen(req, timeout=30) as resp:
        tag = json.load(resp)["tag_name"]
    url = (f"https://github.com/{JB_REPO}/releases/download/"
           f"{tag}/{JB_ASSET}")
    with urllib.request.urlopen(url, timeout=60) as resp:
        return tag, hashlib.sha256(resp.read()).hexdigest()


def inputs(refresh: bool) -> "dict[str, str]":
    """The build inputs: the pinned ones, or today's on a refresh.

    A pin missing any input (a first build) picks it fresh, the same as a
    refresh; nothing ever falls back to a default.
    """
    pin = read_pin()
    out: "dict[str, str]" = {}
    snap = pin.get("CI_APT_SNAPSHOT", "")
    if refresh or not snap:
        snap = _dt.datetime.now(_dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    out["CI_APT_SNAPSHOT"] = snap
    for base in bases():
        k = f"CI_BASE_{key(base)}"
        ref = pin.get(k, "")
        # A pinned digest for a DIFFERENT tag (the base list moved) is not
        # a pin for this one.
        if refresh or not ref.startswith(base.split("@")[0] + "@"):
            ref = f"{base.split('@')[0]}@{_digest(base)}"
        out[k] = ref
    ver, sha = pin.get("CI_JB_VERSION", ""), pin.get("CI_JB_SHA256", "")
    if refresh or not (ver and sha):
        ver, sha = _latest_jb()
    out["CI_JB_VERSION"], out["CI_JB_SHA256"] = ver, sha
    return out


def _pin_keys() -> "list[str]":
    keys = ["CI_APT_SNAPSHOT", "CI_JB_VERSION", "CI_JB_SHA256"]
    for base in bases():
        k = key(base)
        keys += [f"CI_BASE_{k}", f"CI_IMAGE_{k}", f"CI_IMAGE_FINGERPRINT_{k}"]
    return keys + ["CI_IMAGE_SOURCE_HASH"]


def _shape(name: str, value: str) -> bool:
    """Is ``value`` well formed for ``name``?"""
    if name == "CI_APT_SNAPSHOT":
        return re.fullmatch(_SNAPSHOT, value) is not None
    if name == "CI_JB_VERSION":
        return re.fullmatch(r"v?\d+\.\d+\.\d+", value) is not None
    if name.startswith(("CI_BASE_", "CI_IMAGE_")) and not name.startswith(
        ("CI_IMAGE_FINGERPRINT_", "CI_IMAGE_SOURCE")
    ):
        return re.fullmatch(rf"[\w./:-]+@{_DIGEST}", value) is not None
    return re.fullmatch(_HEX64, value) is not None


def write_pin(values: "dict[str, str]", out: Path) -> None:
    """Write the pin, every key present and well formed, in a fixed order.

    Column 0 throughout: make ``include``s this file, and a line with
    leading whitespace reads to make as a recipe outside a target.
    """
    bad = [k for k in _pin_keys() if not _shape(k, values.get(k, ""))]
    if bad:
        sys.exit(f"ci-image: refusing to write a pin with bad {bad}")
    body = "".join(f"{k}={values[k]}\n" for k in _pin_keys())
    out.write_text(HEADER + body, encoding="utf-8")


def changed(new: Path) -> bool:
    """Did the content or the sources move? A new snapshot alone did not."""
    old, fresh = read_pin(), read_pin(new)
    moved = [
        k for k in _pin_keys()
        if k.startswith("CI_IMAGE_FINGERPRINT_") or k == "CI_IMAGE_SOURCE_HASH"
        if old.get(k) != fresh.get(k)
    ]
    for k in moved:
        print(f"{k}: {old.get(k, '<unpinned>')} -> {fresh.get(k)}",
              file=sys.stderr)
    return bool(moved)


def check() -> int:
    """0 when the pin is complete, well formed and built from this tree."""
    if not PIN.exists():
        print(f"ci-image-check: no {PIN}. Dispatch the CI image workflow "
              "to build and pin the first image.")
        return 1
    pin = read_pin()
    bad = [k for k in _pin_keys() if not _shape(k, pin.get(k, ""))]
    if bad:
        print(f"ci-image-check: {PIN} lacks or misforms {bad}")
        return 1
    want = source_hash()
    if pin["CI_IMAGE_SOURCE_HASH"] != want:
        print(
            f"ci-image-check: the image's sources ({DOCKERFILE}, {EXTRA}, "
            f"{BOOTSTRAP}) moved without a repin.\n"
            f"  pinned: {pin['CI_IMAGE_SOURCE_HASH']}\n"
            f"  tree:   {want}\n"
            "  A push of this branch builds the image and commits its pin; "
            "or dispatch the CI image workflow on it."
        )
        return 1
    print(f"ci-image-check: {PIN} pins images built from this tree")
    return 0


def main(argv: "list[str]") -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("source-hash")
    p = sub.add_parser("inputs")
    p.add_argument("--refresh", action="store_true")
    p = sub.add_parser("key")
    p.add_argument("base")
    p = sub.add_parser("join-fingerprint")
    p.add_argument("fp", nargs="+")
    p = sub.add_parser("write-pin")
    p.add_argument("--out", type=Path, default=PIN)
    p = sub.add_parser("changed")
    p.add_argument("--new", type=Path, required=True)
    sub.add_parser("check")
    a = ap.parse_args(argv)

    if a.cmd == "source-hash":
        print(source_hash())
    elif a.cmd == "inputs":
        for k, v in inputs(a.refresh).items():
            print(f"{k}={v}")
    elif a.cmd == "key":
        print(key(a.base))
    elif a.cmd == "join-fingerprint":
        print(join_fingerprint(a.fp))
    elif a.cmd == "write-pin":
        values = {}
        for line in sys.stdin:
            if "=" in line:
                k, _, v = line.strip().partition("=")
                values[k] = v
        write_pin(values, a.out)
    elif a.cmd == "changed":
        print(f"changed={1 if changed(a.new) else 0}")
    elif a.cmd == "check":
        return check()
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
