#!/usr/bin/env python3
"""Regenerate ``src/just_makeit/_installhistory.py`` (gh-1589).

`jm adopt --packaging` hands an existing project's root install section to
jm only when nothing the author wrote would be lost. The section to replace
was rendered by some older jm, and jm cannot tell an older jm's command from
one an author added by reading it -- so it asks the table this writes: every
CMake command any released jm rendered in that section, in TEMPLATE form
(``<<project>>`` placeholders intact), read from the template at each ``v*``
tag.

The table only ever grows. It is the existing table, plus every tag this
clone can see, plus the current template. That is what lets it run where
there are no tags (a shallow CI checkout): it then adds the current
template's commands and drops nothing. A gate
(``tests/test_gh1589_install_block.py``) fails when the current template
renders a command the table lacks, so a template change arrives with its
table update -- and the next release's section is already in it.

Usage: ``make install-history-update``.
"""

from __future__ import annotations

import importlib
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from just_makeit import _rootcmake as R  # noqa: E402

#: A bracket-argument opener as a word of its own (see ``main``).
_OPEN = re.compile(r"^\[=*\[$")

TEMPLATE = "src/just_makeit/templates/cmake/CMakeLists_top.cmake"
#: The packaging templates whose LINES are recorded the same way, so adopting
#: a token-less `cmake/*.in` keeps an older jm's spelling of a line.
IN_TEMPLATES = (
    "src/just_makeit/templates/cmake/package.pc.in",
    "src/just_makeit/templates/cmake/packageConfig.cmake.in",
)
OUT = ROOT / "src" / "just_makeit" / "_installhistory.py"


def section(text: str) -> "str | None":
    """The install section of a root template: from the ``# ── Install``
    header to the end sentinel, or to the end of the file before there was
    one."""
    begin = R.INSTALL_BEGIN.search(text)
    if not begin:
        return None
    end = R.INSTALL_END.search(text, begin.end())
    return text[begin.end() : end.start() if end else len(text)]


def calls_of(text: str) -> "set[tuple[str, tuple[str, ...]]]":
    sec = section(text)
    return set() if sec is None else {(c.name, c.args) for c in R.calls(sec)}


def lines_of(text: str) -> "set[str]":
    """The lines that carry content: blank and ``#`` comment lines aside."""
    return {
        ln.strip()
        for ln in text.splitlines()
        if ln.strip() and not ln.lstrip().startswith("#")
    }


def main() -> int:
    known: set = set()
    lines: set = set()
    if OUT.exists():
        old = importlib.import_module("just_makeit._installhistory")
        # gh-1604: `calls()` reads a bracket argument as ONE word. An entry
        # recorded before that holds its `[[` as a word of its own, and can
        # never match what the parser produces now -- drop it; the tags and
        # the current template below re-add the command in its real form.
        known |= {
            c for c in old.CALLS if not any(_OPEN.match(w) for w in c[1])
        }
        lines |= set(getattr(old, "LINES", ()))
    tags = subprocess.run(
        ["git", "tag", "-l", "v*", "--sort=v:refname"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.split()
    for tag in tags:
        r = subprocess.run(
            ["git", "show", f"{tag}:{TEMPLATE}"],
            cwd=ROOT,
            capture_output=True,
            text=True,
        )
        if r.returncode == 0:
            known |= calls_of(r.stdout)
        for path in IN_TEMPLATES:
            r = subprocess.run(
                ["git", "show", f"{tag}:{path}"],
                cwd=ROOT,
                capture_output=True,
                text=True,
            )
            if r.returncode == 0:
                lines |= lines_of(r.stdout)
    known |= calls_of((ROOT / TEMPLATE).read_text(encoding="utf-8"))
    for path in IN_TEMPLATES:
        lines |= lines_of((ROOT / path).read_text(encoding="utf-8"))
    body = "".join(f"        {c!r},\n" for c in sorted(known))
    lbody = "".join(f"        {ln!r},\n" for ln in sorted(lines))
    OUT.write_text(
        '"""Every command a released jm rendered in the root install section.\n'
        "\n"
        "GENERATED by ``make install-history-update``"
        " (``scripts/install_history.py``);\n"
        "do not edit. Template form: ``<<project>>`` and\n"
        "``<<project_underscore>>`` are rendered with a project's names before\n"
        "comparing (gh-1589).\n"
        '"""\n'
        "\n"
        "CALLS: frozenset = frozenset(\n"
        "    {\n" + body + "    }\n"
        ")\n"
        "\n"
        "#: Every content line a released jm rendered in cmake/<pkg>.pc.in and\n"
        "#: cmake/<pkg>-config.cmake.in, the same way.\n"
        "LINES: frozenset = frozenset(\n"
        "    {\n" + lbody + "    }\n"
        ")\n",
        encoding="utf-8",
        newline="\n",
    )
    print(
        f"{OUT.relative_to(ROOT)}: {len(known)} commands,"
        f" {len(lines)} template lines, {len(tags)} tags"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
