"""Every command a released jm rendered in the root install section.

GENERATED by ``make install-history-update`` (``scripts/install_history.py``);
do not edit. Template form: ``<<project>>`` and
``<<project_underscore>>`` are rendered with a project's names before
comparing (gh-1589).
"""

CALLS: frozenset = frozenset(
    {
        (
            "configure_file",
            ("cmake/<<project>>.pc.in", "<<project>>.pc", "@ONLY"),
        ),
        (
            "configure_file",
            ("cmake/<<project>>.pc.in", "<<project>>.pc.configured", "@ONLY"),
        ),
        (
            "configure_file",
            (
                "cmake/<<project_underscore>>.pc.in",
                "<<project_underscore>>.pc.configured",
                "@ONLY",
            ),
        ),
        (
            "configure_package_config_file",
            (
                "cmake/<<project_underscore>>-config.cmake.in",
                "${CMAKE_CURRENT_BINARY_DIR}/<<project_underscore>>-config.cmake",
                "INSTALL_DESTINATION",
                "${CMAKE_INSTALL_LIBDIR}/cmake/<<project_underscore>>",
            ),
        ),
        ("else", ()),
        ("elseif", ("CMAKE_VERSION", "VERSION_LESS", "3.17")),
        ("endif", ()),
        (
            "export",
            (
                "EXPORT",
                "<<project_underscore>>-targets",
                "FILE",
                "${CMAKE_CURRENT_BINARY_DIR}/<<project_underscore>>-targets.cmake",
                "NAMESPACE",
                "<<project_underscore>>::",
            ),
        ),
        ("if", ("IS_ABSOLUTE", "${CMAKE_INSTALL_INCLUDEDIR}")),
        ("if", ("IS_ABSOLUTE", "${CMAKE_INSTALL_LIBDIR}")),
        ("if", ("JM_MATH_LIBRARY",)),
        ("if", ("NOT", "${JM_PC_LIBS_PRIVATE}", "STREQUAL", "")),
        ("if", ("NOT", "${JM_PC_REQUIRES_PRIVATE}", "STREQUAL", "")),
        ("if", ("NOT", "PROJECT_HOMEPAGE_URL", "STREQUAL", "")),
        ("if", ("PROJECT_VERSION_MAJOR", "EQUAL", "0")),
        ("include", ("CMakePackageConfigHelpers",)),
        ("include", ("GNUInstallDirs",)),
        (
            "install",
            (
                "CODE",
                '\nfile(READ "${JM_PC_FILE}.configured" _jm_pc)\nstring(REPLACE "%JM_INSTALL_PREFIX%" "${CMAKE_INSTALL_PREFIX}" _jm_pc "${_jm_pc}")\nfile(WRITE "${JM_PC_FILE}" "${_jm_pc}")\n',
            ),
        ),
        (
            "install",
            (
                "CODE",
                '\nfile(READ "${JM_PC_FILE}.configured" _jm_pc)\nstring(REPLACE "%JM_INSTALL_PREFIX%" "${CMAKE_INSTALL_PREFIX}" _jm_pc "${_jm_pc}")\nfile(WRITE "${JM_PC_FILE}" "${_jm_pc}")\n',
                "COMPONENT",
                "dev",
            ),
        ),
        (
            "install",
            (
                "CODE",
                'set(JM_PC_FILE \\"${CMAKE_CURRENT_BINARY_DIR}/<<project>>.pc\\")',
            ),
        ),
        (
            "install",
            (
                "CODE",
                'set(JM_PC_FILE \\"${CMAKE_CURRENT_BINARY_DIR}/<<project_underscore>>.pc\\")',
            ),
        ),
        (
            "install",
            (
                "CODE",
                'set(JM_PC_FILE \\"${CMAKE_CURRENT_BINARY_DIR}/<<project_underscore>>.pc\\")',
                "COMPONENT",
                "dev",
            ),
        ),
        (
            "install",
            (
                "DIRECTORY",
                "${CMAKE_SOURCE_DIR}/<<inc_dir>>/",
                "DESTINATION",
                "${CMAKE_INSTALL_INCLUDEDIR}",
                "COMPONENT",
                "dev",
                "FILES_MATCHING",
                "PATTERN",
                "*.h",
                "PATTERN",
                "pyex_common.h",
                "EXCLUDE",
            ),
        ),
        (
            "install",
            (
                "DIRECTORY",
                "${CMAKE_SOURCE_DIR}/<<inc_dir>>/",
                "DESTINATION",
                "${CMAKE_INSTALL_INCLUDEDIR}",
                "FILES_MATCHING",
                "PATTERN",
                "*.h",
                "PATTERN",
                "pyex_common.h",
                "EXCLUDE",
            ),
        ),
        (
            "install",
            (
                "DIRECTORY",
                "${CMAKE_SOURCE_DIR}/native/inc/",
                "DESTINATION",
                "${CMAKE_INSTALL_INCLUDEDIR}",
                "FILES_MATCHING",
                "PATTERN",
                "*.h",
                "PATTERN",
                "pyex_common.h",
                "EXCLUDE",
            ),
        ),
        (
            "install",
            (
                "EXPORT",
                "<<project_underscore>>-targets",
                "FILE",
                "<<project_underscore>>-targets.cmake",
                "NAMESPACE",
                "<<project_underscore>>::",
                "DESTINATION",
                "${CMAKE_INSTALL_LIBDIR}/cmake/<<project_underscore>>",
            ),
        ),
        (
            "install",
            (
                "EXPORT",
                "<<project_underscore>>-targets",
                "FILE",
                "<<project_underscore>>-targets.cmake",
                "NAMESPACE",
                "<<project_underscore>>::",
                "DESTINATION",
                "${CMAKE_INSTALL_LIBDIR}/cmake/<<project_underscore>>",
                "COMPONENT",
                "dev",
            ),
        ),
        (
            "install",
            (
                "FILES",
                "${CMAKE_CURRENT_BINARY_DIR}/<<project>>.pc",
                "DESTINATION",
                "${CMAKE_INSTALL_LIBDIR}/pkgconfig",
            ),
        ),
        (
            "install",
            (
                "FILES",
                "${CMAKE_CURRENT_BINARY_DIR}/<<project_underscore>>-config.cmake",
                "${CMAKE_CURRENT_BINARY_DIR}/<<project_underscore>>-config-version.cmake",
                "DESTINATION",
                "${CMAKE_INSTALL_LIBDIR}/cmake/<<project_underscore>>",
            ),
        ),
        (
            "install",
            (
                "FILES",
                "${CMAKE_CURRENT_BINARY_DIR}/<<project_underscore>>-config.cmake",
                "${CMAKE_CURRENT_BINARY_DIR}/<<project_underscore>>-config-version.cmake",
                "DESTINATION",
                "${CMAKE_INSTALL_LIBDIR}/cmake/<<project_underscore>>",
                "COMPONENT",
                "dev",
            ),
        ),
        (
            "install",
            (
                "FILES",
                "${CMAKE_CURRENT_BINARY_DIR}/<<project_underscore>>.pc",
                "DESTINATION",
                "${CMAKE_INSTALL_LIBDIR}/pkgconfig",
            ),
        ),
        (
            "install",
            (
                "FILES",
                "${CMAKE_CURRENT_BINARY_DIR}/<<project_underscore>>.pc",
                "DESTINATION",
                "${CMAKE_INSTALL_LIBDIR}/pkgconfig",
                "COMPONENT",
                "dev",
            ),
        ),
        (
            "install",
            (
                "TARGETS",
                "<<project_underscore>>_lib",
                "<<project_underscore>>_lib_static",
                "EXPORT",
                "<<project_underscore>>-targets",
                "LIBRARY",
                "DESTINATION",
                "${CMAKE_INSTALL_LIBDIR}",
                "ARCHIVE",
                "DESTINATION",
                "${CMAKE_INSTALL_LIBDIR}",
            ),
        ),
        (
            "install",
            (
                "TARGETS",
                "<<project_underscore>>_lib",
                "<<project_underscore>>_lib_static",
                "EXPORT",
                "<<project_underscore>>-targets",
                "RUNTIME",
                "DESTINATION",
                "${CMAKE_INSTALL_BINDIR}",
                "COMPONENT",
                "runtime",
                "LIBRARY",
                "DESTINATION",
                "${CMAKE_INSTALL_LIBDIR}",
                "COMPONENT",
                "runtime",
                "NAMELINK_COMPONENT",
                "dev",
                "ARCHIVE",
                "DESTINATION",
                "${CMAKE_INSTALL_LIBDIR}",
                "COMPONENT",
                "dev",
            ),
        ),
        (
            "install",
            (
                "TARGETS",
                "<<project_underscore>>_lib",
                "<<project_underscore>>_lib_static",
                "EXPORT",
                "<<project_underscore>>-targets",
                "RUNTIME",
                "DESTINATION",
                "${CMAKE_INSTALL_BINDIR}",
                "LIBRARY",
                "DESTINATION",
                "${CMAKE_INSTALL_LIBDIR}",
                "ARCHIVE",
                "DESTINATION",
                "${CMAKE_INSTALL_LIBDIR}",
            ),
        ),
        ("set", ("JM_ABI_VERSION", "${PROJECT_VERSION_MAJOR}")),
        (
            "set",
            (
                "JM_ABI_VERSION",
                "${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}",
            ),
        ),
        (
            "set",
            (
                "JM_INSTALL_NAME_DIR",
                "$<INSTALL_PREFIX>/${CMAKE_INSTALL_LIBDIR}",
            ),
        ),
        ("set", ("JM_INSTALL_NAME_DIR", "${CMAKE_INSTALL_FULL_LIBDIR}")),
        ("set", ("JM_INSTALL_NAME_DIR", "${CMAKE_INSTALL_LIBDIR}")),
        ("set", ("JM_PC_EXTRA_FIELDS", "")),
        ("set", ("JM_PC_INCLUDEDIR", "${CMAKE_INSTALL_INCLUDEDIR}")),
        (
            "set",
            ("JM_PC_INCLUDEDIR", "\\${prefix}/${CMAKE_INSTALL_INCLUDEDIR}"),
        ),
        ("set", ("JM_PC_LIBDIR", "${CMAKE_INSTALL_LIBDIR}")),
        ("set", ("JM_PC_LIBDIR", "\\${exec_prefix}/${CMAKE_INSTALL_LIBDIR}")),
        ("set", ("JM_PC_LIBM", "")),
        ("set", ("JM_PC_LIBM", " -lm")),
        ("set", ("JM_PC_PREFIX", "%JM_INSTALL_PREFIX%")),
        ("set", ("JM_VERSION_COMPATIBILITY", "SameMajorVersion")),
        ("set", ("JM_VERSION_COMPATIBILITY", "SameMinorVersion")),
        (
            "set_target_properties",
            (
                "<<project_underscore>>_lib",
                "PROPERTIES",
                "EXPORT_NAME",
                "<<project_underscore>>",
            ),
        ),
        (
            "set_target_properties",
            (
                "<<project_underscore>>_lib",
                "PROPERTIES",
                "INSTALL_NAME_DIR",
                "${JM_INSTALL_NAME_DIR}",
            ),
        ),
        (
            "set_target_properties",
            (
                "<<project_underscore>>_lib",
                "PROPERTIES",
                "VERSION",
                "${PROJECT_VERSION}",
                "SOVERSION",
                "${JM_ABI_VERSION}",
            ),
        ),
        (
            "set_target_properties",
            (
                "<<project_underscore>>_lib_static",
                "PROPERTIES",
                "EXPORT_NAME",
                "<<project_underscore>>-static",
            ),
        ),
        (
            "string",
            ("APPEND", "JM_PC_EXTRA_FIELDS", "${JM_PC_LIBS_PRIVATE}\\n"),
        ),
        (
            "string",
            ("APPEND", "JM_PC_EXTRA_FIELDS", "${JM_PC_REQUIRES_PRIVATE}\\n"),
        ),
        (
            "string",
            (
                "APPEND",
                "JM_PC_EXTRA_FIELDS",
                "URL: ${PROJECT_HOMEPAGE_URL}\\n",
            ),
        ),
        (
            "write_basic_package_version_file",
            (
                "${CMAKE_CURRENT_BINARY_DIR}/<<project_underscore>>-config-version.cmake",
                "VERSION",
                "${PROJECT_VERSION}",
                "COMPATIBILITY",
                "${JM_VERSION_COMPATIBILITY}",
            ),
        ),
        (
            "write_basic_package_version_file",
            (
                "${CMAKE_CURRENT_BINARY_DIR}/<<project_underscore>>-config-version.cmake",
                "VERSION",
                "${PROJECT_VERSION}",
                "COMPATIBILITY",
                "SameMajorVersion",
            ),
        ),
    }
)

#: Every content line a released jm rendered in cmake/<pkg>.pc.in and
#: cmake/<pkg>-config.cmake.in, the same way.
LINES: frozenset = frozenset(
    {
        "@JM_FIND_DEPENDENCIES@",
        "@JM_PC_EXTRA_FIELDS@Version: @PROJECT_VERSION@",
        "@PACKAGE_INIT@",
        "Cflags: -I${includedir}",
        "Cflags: -I${includedir}@JM_PC_CFLAGS@",
        "Description: <<project>> C library",
        "Description: @PROJECT_DESCRIPTION@",
        "Libs: -L${libdir} -l<<project_underscore>>",
        "Libs: -L${libdir} -l<<project_underscore>>@JM_PC_LIBM@",
        "Name: <<project>>",
        "Name: <<project_underscore>>",
        "Version: @PROJECT_VERSION@",
        "check_required_components(<<project_underscore>>)",
        "exec_prefix=${prefix}",
        'include("${CMAKE_CURRENT_LIST_DIR}/<<project_underscore>>-targets.cmake")',
        "includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@",
        "includedir=@JM_PC_INCLUDEDIR@",
        "libdir=${exec_prefix}/@CMAKE_INSTALL_LIBDIR@",
        "libdir=@JM_PC_LIBDIR@",
        "prefix=@CMAKE_INSTALL_PREFIX@",
        "prefix=@JM_PC_PREFIX@",
    }
)
