"""End-to-end: upgrade a project jm 0.33.14 generated, with the current jm.

Two jobs, one run (gh-1443):

* **Show a user how to upgrade.** ``tree/`` is a real project, generated by
  the released jm 0.33.14 (``FREEZE.toml`` records exactly how) and carrying
  its author's kernel in the sacred header. This walks the upgrade a user
  does: read ``jm status``, ``jm apply``, ``jm upgrade``, receive the fix a
  stale binding fragment is missing, adopt the create-only files jm ships
  newer, and prove it -- ``jm status --check`` clean, built, tested, and the
  strided ``out=`` that 0.33.14's binding silently ignored now refused.
* **Catch the regression an upgrading project would meet.** Every defect in
  five releases on 2026-09-21 was found by doppler adopting the release, and
  the recurring shape was a fragment rendered by an OLDER jm meeting a guard
  added later. A fresh scaffold cannot show that class: it is rendered by the
  jm under test. So what each step prints is compared with ``upgrade.golden``.
  A release that changes it on purpose regenerates the golden in the same PR
  and the diff is reviewed; any other change is a regression::

      JM_UPDATE_STALE_GOLDEN=1 make test-examples EXAMPLES_K=stale_project

**The tree is never refreshed.** A stray ``apply`` or a formatter sweep over
it would make every report go quiet and this pass forever after, so the run
first proves the tree is still the one that was frozen: its manifest still
carries the frozen ``jm_version`` and every file still hashes to
``tree.sha256``. And it is never RE-frozen: the golden growing is the record
of every guard added since 0.33.14. If jm ever deliberately stops applying
it, freeze a second project beside it and keep both.

Called by tests/test_examples.py via run(root).
Also runnable directly: python3 src/just_makeit/examples/stale_project/test.py
"""

from __future__ import annotations

import contextlib
import hashlib
import io
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).parent
TREE = HERE / "tree"
GOLDEN = HERE / "upgrade.golden"
UPDATE = os.environ.get("JM_UPDATE_STALE_GOLDEN") == "1"

# numpy spells a buffer it cannot write through, for every out= path jm emits.
_OUT_REFUSED = "out must be a writable, C-contiguous ndarray"

_DEMO = """
import sys
sys.path.insert(0, {src!r})
import numpy as np
from stale.dsp import Fir

f = Fir()
f.scale = 2.0
x = np.ones(8, np.float32)

# The author's kernel survived the upgrade: y = x * scale.
y = f.steps(x)
assert y.tolist() == [2.0] * 8, y

# A contiguous out= is filled in place.
out = np.zeros(8, np.float32)
assert f.steps(x, out=out) is out and out.tolist() == [2.0] * 8, out

# A strided out= -- every other element of a longer array.
strided = np.zeros(16, np.float32)[::2]
try:
    r = f.steps(x, out=strided)
except TypeError as e:
    print("REFUSED", e)
else:
    print("ACCEPTED", r is strided, strided.tolist())
"""


def _frozen() -> str:
    """The version the tree was frozen at, after proving it still is."""
    from just_makeit import _config as C

    freeze = C.tomllib.loads(
        (HERE / "FREEZE.toml").read_text(encoding="utf-8")
    )
    manifest = C.tomllib.loads(
        (TREE / "just-makeit.toml").read_text(encoding="utf-8")
    )
    assert manifest["project"]["jm_version"] == freeze["jm_version"], (
        "stale_project/tree was re-stamped -- an `apply` ran over it. Restore "
        "it with `git checkout`; it is never regenerated."
    )
    recorded = {}
    for line in (
        (HERE / "tree.sha256").read_text(encoding="utf-8").splitlines()
    ):
        digest, rel = line.split(maxsplit=1)
        recorded[rel[2:] if rel.startswith("./") else rel] = digest
    actual = {
        p.relative_to(TREE).as_posix(): hashlib.sha256(
            p.read_bytes()
        ).hexdigest()
        for p in TREE.rglob("*")
        if p.is_file() and "__pycache__" not in p.parts
    }
    changed = sorted(
        rel
        for rel in set(recorded) | set(actual)
        if recorded.get(rel) != actual.get(rel)
    )
    assert not changed, (
        f"stale_project/tree changed: {changed}. A formatter or a sweep "
        "reached it; restore it with `git checkout`."
    )
    return freeze["jm_version"]


class _Log:
    """What each jm command printed, as the user would read it."""

    def __init__(self, proj: Path) -> None:
        from just_makeit import __version__

        self.proj = proj
        self.version = __version__
        self.parts: list[str] = []

    def jm(self, *args: str, expect: int = 0) -> str:
        """Run ``just-makeit <args>`` in the project and record its output.

        In-process, like the other examples: one buffer for both streams, so
        warnings sit where the terminal would show them.
        """
        from just_makeit._cli import main

        buf = io.StringIO()
        argv, cwd = sys.argv, os.getcwd()
        sys.argv = ["just-makeit", *args]
        os.chdir(self.proj)
        code = 0
        try:
            with (
                contextlib.redirect_stdout(buf),
                contextlib.redirect_stderr(buf),
            ):
                try:
                    main()
                except SystemExit as e:
                    code = e.code if isinstance(e.code, int) else 1
        finally:
            sys.argv = argv
            os.chdir(cwd)
        text = buf.getvalue()
        assert code == expect, f"jm {' '.join(args)} exited {code}\n{text}"
        # The copy's location and the running version are the only inputs
        # that differ between runs, and neither is what this is about.
        norm = (
            text.replace(str(self.proj) + os.sep, "")
            .replace(str(self.proj), ".")
            .replace(self.version, "<HEAD>")
        )
        if os.sep != "/":
            # jm prints paths the way the platform spells them; the golden is
            # one file for every platform.
            norm = norm.replace(os.sep, "/")
        self.parts.append(f"$ jm {' '.join(args)}   # exit {code}\n{norm}")
        return text

    def report(self) -> str:
        return "\n".join(self.parts)


def _cmd(args, cwd) -> str:
    r = subprocess.run(
        args, cwd=cwd, capture_output=True, text=True, timeout=900
    )
    assert r.returncode == 0, (
        f"{' '.join(map(str, args))} exited {r.returncode}\n"
        f"{r.stdout}\n{r.stderr}"
    )
    return r.stdout


def _build_and_demo(proj: Path, build: str) -> str:
    """Configure fresh, build, run the C tests, and run the Python demo.

    The build tree goes BESIDE the project, not in it: `jm status` counts
    every file under the project, and a build tree's file count is the
    toolchain's, not jm's -- the golden would differ between machines.
    """
    bdir = proj.parent / build
    _cmd(
        [
            "cmake",
            "-S",
            str(proj),
            "-B",
            str(bdir),
            f"-DPython3_EXECUTABLE={sys.executable}",
        ],
        proj,
    )
    _cmd(["cmake", "--build", str(bdir)], proj)
    _cmd(["ctest", "--test-dir", str(bdir), "--output-on-failure"], proj)
    return _cmd(
        [sys.executable, "-c", _DEMO.format(src=str(proj / "src"))], proj
    )


def _set_object_key(path: Path, table: str, line: str) -> None:
    """Put *line* under ``[table]`` -- not at the end of the file.

    Appending would land it inside the last sub-table (``[[fir.properties]]``
    here), where jm reads it as a property key and says it has no effect.
    """
    text = path.read_text(encoding="utf-8")
    header = f"[{table}]\n"
    assert text.count(header) == 1, text
    path.write_text(
        text.replace(header, header + line + "\n"), encoding="utf-8"
    )


def run(root: Path) -> None:
    frozen = _frozen()

    # ── 1. A project an old jm generated ──────────────────────────────────
    proj = root / "stale"
    shutil.copytree(TREE, proj)
    log = _Log(proj)

    # ── 2. What is behind: read before you write ─────────────────────────
    # Exit 1: files the manifest implies are missing or stale.
    log.jm("status", expect=1)

    # ── 3. jm apply: everything the manifest implies that is missing ─────
    # It stamps the manifest with this jm's version and warns, loudly, about
    # the binding fragment 0.33.14 rendered without the out= contiguity test.
    applied = log.jm("apply")
    assert f"generated with just-makeit {frozen}" in applied
    assert "C-contiguity and this fragment does not" in applied
    log.jm("status")

    # ── 4. The root CMakeLists.txt, which jm maintains only in part ──────
    # apply splices its marked blocks (components, modules, external deps)
    # and nothing else, and status does not compare the rest (gh-959) -- so
    # every root-template fix since 0.33.14 is missing in silence, among them
    # the Windows ones: without them this project does not build under
    # clang-cl (`multiple rules generate stale.lib`, gh-1471). Today's render
    # comes from a scratch `jm new` of the same name; merge it into yours --
    # here, never edited, it is taken whole -- and apply re-splices the rest.
    from just_makeit._new import run as jm_new

    with contextlib.redirect_stdout(io.StringIO()):
        jm_new("stale", root / "fresh" / "stale")
    shutil.copyfile(
        root / "fresh" / "stale" / "CMakeLists.txt", proj / "CMakeLists.txt"
    )
    log.jm("apply")

    # ── 5. jm upgrade, and the create-only files jm ships newer ──────────
    # One step, because they go together: upgrade respells `complex` as
    # `_Complex` (gh-1246), which only the NEW clib_common.h reads everywhere
    # -- both or neither. clang-cl rejects the old spelling outright.
    log.jm("upgrade")
    # status names the create-only files OUTDATED. apply never rewrites one:
    # yours to adopt. Diff each first -- none was edited here, so each takes
    # jm's render the same way, by deleting it and letting apply write today's.
    outdated = re.findall(r"^  ↑ (\S+)$", log.jm("status"), re.MULTILINE)
    assert "native/inc/clib_common.h" in outdated, outdated
    for rel in outdated:
        (proj / rel).unlink()
    # jb.toml was renamed bootstrap.toml (gh-935). Step 3's apply held the
    # new one back and said why; upgrade, above, moved the old one across --
    # and, never edited here, it is OUTDATED like the rest and was just
    # deleted, so the apply below writes today's.
    assert not (proj / "jb.toml").exists()
    # The scaffolded C benchmarks are the AUTHOR's once written, so status
    # cannot call them behind -- but 0.33.14's time with POSIX clock_gettime,
    # which Windows lacks. Never edited here, so they take today's render,
    # which times through jm_bench.h on every platform.
    for bench in sorted((proj / "native/benchmarks").glob("bench_*_core.c")):
        if "clock_gettime" in bench.read_text(encoding="utf-8"):
            bench.unlink()
    log.jm("apply")

    assert (proj / "bootstrap.toml").is_file()

    # ── 6. What the fragment warning means, in running code ──────────────
    # The project builds everywhere now -- and the binding 0.33.14 rendered
    # fills a strided out= through a temporary copy, handing the caller's
    # buffer back untouched.
    before = _build_and_demo(proj, "build-before")
    assert "ACCEPTED" in before and "0.0" in before, before

    # ── 7. Receive the fix the binding fragment is missing ────────────────
    # A module object's fragment is sacred: apply only ever ADDS to it, so a
    # fix to a member it already has never arrives. adopt --check says which
    # units differ from today's render; nobody wrote code in this one, so the
    # answer is to take the render -- delete it, and apply writes it fresh.
    log.jm("adopt", "--check", expect=1)
    (proj / "native/src/dsp/dsp_ext_fir.c").unlink()
    log.jm("apply")
    # Now it matches, and `fragment = "generated"` makes it jm's for good:
    # the next fix to a wrapper arrives on the next apply by itself.
    log.jm("adopt", "--check")
    _set_object_key(proj / "objects/fir.toml", "fir", 'fragment = "generated"')
    log.jm("apply")

    # ── 8. Done: nothing behind, and it builds and runs ───────────────────
    log.jm("status", "--check")
    after = _build_and_demo(proj, "build")
    assert "REFUSED" in after and _OUT_REFUSED in after, after

    # The author's kernel came through every step untouched.
    assert "return x * state->scale;" in (
        proj / "native/inc/fir/fir_core.h"
    ).read_text(encoding="utf-8")

    # ── the regression half: what every step printed ─────────────────────
    report = log.report()
    if UPDATE:
        GOLDEN.write_text(report, encoding="utf-8", newline="\n")
    assert GOLDEN.exists(), (
        "no upgrade.golden; create it deliberately with "
        "JM_UPDATE_STALE_GOLDEN=1 make test-examples EXAMPLES_K=stale_project"
    )
    golden = GOLDEN.read_text(encoding="utf-8")
    # An empty golden is a defect in the gate, not a clean bill.
    assert "warning" in golden and "OUTDATED" in golden, (
        "upgrade.golden says nothing -- blanked, or the tree is no longer "
        "stale"
    )
    import difflib

    diff = "".join(
        difflib.unified_diff(
            golden.splitlines(keepends=True),
            report.splitlines(keepends=True),
            "upgrade.golden",
            "this run",
        )
    )
    assert report == golden, (
        diff
        + "\n"
        + (
            "What upgrading the frozen 0.33.14 project prints changed. If the "
            "release means it (a guard added on purpose), regenerate with "
            "JM_UPDATE_STALE_GOLDEN=1 make test-examples "
            "EXAMPLES_K=stale_project and let the diff be reviewed; otherwise it "
            "is a regression an upgrading project would meet."
        )
    )


if __name__ == "__main__":
    import tempfile

    with tempfile.TemporaryDirectory() as d:
        run(Path(d))
    print("stale_project: OK")
